version:
  name: velociraptor
  version: 0.7.0-2
  commit: 82f2cada
  build_time: "2023-09-10T16:24:02Z"
  install_time: 1697009029
  compiler: go1.19.13
Client:
  server_urls:
  - https://192.168.56.105:9000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRAPOOrpNQNN+CVUV8gBRXfpYwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIzMTAxMTA3MjQzNloXDTMz
    MTAwODA3MjQzNlowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA71API+h59I1p0kwptTHpCDNDUjwgpfdM
    PiZqEGfcnHaUi+7Vr3ZwWXiPVYXaqiDr50h18oF08o7CYG8fYMcEAIIsHc04zseZ
    wrMYFbkxgEmIbXHJAHNFxsAAkha5cTMimhtPLvHt/R57W8HvE77xJ+xS0X+L1AMD
    YaGo/TAXh/insb4htfHsPurIEc1GWC8c2SOn5FiFSf1cu4zMfJTMXoMo00sNLJMy
    MLFR6rgRjlYVuC3qS9rlxgfv0MHl7GWFoXiwIur26tXBozl9eikID72xwGt69VXl
    BGHjAUxhJBsGWwO/dYMrjs8iD2qcT9iZzhYB5odlyzMOH91VCGKb+wIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUmsnOHOeRYnNWnSp2x0iXbZF9
    gHYwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAECDJ3ODUtr9zV3aD0ezHESjoYR2yvGhxBA+i334Gw7P
    cBn9A0W8SB62p7qs1dDQj80A2qeMu/eCuqSfBjt+jV1Cc/LAXgocQpnkZPF3LKDP
    yjJ7zzA99BOvoc3QNhG7DfVrXjaJlamjx1RPEU/9Y8W61wHN1yQlIxE9YP6wsYPN
    klm9RgozIw3U57BWgIXPPu0l0gcJWraIaRrP4bG814FjlA0+QdqCYLas+FwVTqYy
    x0ZQjWtWQxHwFvc7oFBGXUDTlJahxrDdGYxAa+WC8g3NVvIKOgwpoxSB0pRzVIc7
    UTR/l+9K3gbJp+4zCeZ99KBR0PQs6G+7V1qTrS0sq6M=
    -----END CERTIFICATE-----
  nonce: JoJqIltvjKQ=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.0-2
    commit: 82f2cada
    build_time: "2023-09-10T16:24:02Z"
    install_time: 1697009029
    compiler: go1.19.13
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
